server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #Nacos服务注册中心地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如呗占用会自动8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      web-context-unify: false
      filter:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"