server:
  port: 85

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #Nacos服务注册中心地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如呗占用会自动8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      web-context-unify: false
      filter:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

#消费者将要去注册中心访问的的服务提供者名称
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对Feign的支持
feign:
  sentinel:
    enabled: true